module.exports = {
  '--moonlight-desaturated-gray': '#7f85a3',
  '--moonlight-dark-blue': '#3e68d7',
  '--moonlight-blue-alt': '#4EADE5',
  '--moonlight-blue': '#70B0FF',
  '--moonlight-sky-blue': '#65bcff',
  '--moonlight-cyan': '#7FDAFF',
  '--moonlight-red': '#ff757f',
  '--moonlight-dark-red': '#ff5370',
  '--moonlight-light-red': '#ff98a4',
  '--moonlight-yellow-alt': '#FFC66D',
  '--moonlight-yellow': '#FFDB8E',
  '--moonlight-orange': '#ff966c',
  '--moonlight-dark-orange': '#fc7b7b',
  '--moonlight-teal-alt': '#20999D',
  '--moonlight-teal': '#34D3FB',
  '--moonlight-green': '#7AF8CA',
  '--moonlight-purple': '#BAACFF',
  '--moonlight-pink': '#F3C1FF',
  '--moonlight-indigo': '#7E8EDA',
  '--moonlight-bright-cyan': '#b4f9f8',

  '--moonlight-gray-11': '#E4F3FA',
  '--moonlight-gray-10-alt': '#bcc4d6',
  '--moonlight-gray-10': '#c8d3f5',
  '--moonlight-gray-9': '#b4c2f0',
  '--moonlight-gray-8': '#a9b8e8',
  '--moonlight-gray-7': '#828bb8',
  '--moonlight-gray-6': '#444a73',
  '--moonlight-gray-5': '#2f334d',
  '--moonlight-gray-4': '#222436',
  '--moonlight-gray-3': '#1e2030',
  '--moonlight-gray-2': '#191a2a',
  '--moonlight-gray-1': '#131421'
};
